name: pokeproyecto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  http: ^1.2.1
  flutter_radar: ^3.12.4
  flutter_radar_chart: ^0.2.1
  cloud_firestore: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logotipo.png
    - assets/images/pokebola.png
    - assets/images/banner.png
