// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiJxyP2GwIJ6F11rCegB6qk5rFGTx9Eo4',
    appId: '1:490084819177:web:e06bb42b401e36600b1078',
    messagingSenderId: '490084819177',
    projectId: 'pokeproyecto-9c799',
    authDomain: 'pokeproyecto-9c799.firebaseapp.com',
    storageBucket: 'pokeproyecto-9c799.firebasestorage.app',
    measurementId: 'G-THFZ2Y96J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhD9x-IhmiXt38J70W57n833cRWbmJ8Rg',
    appId: '1:490084819177:android:e6b1f53b97f4e3440b1078',
    messagingSenderId: '490084819177',
    projectId: 'pokeproyecto-9c799',
    storageBucket: 'pokeproyecto-9c799.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQx06FJSrzCW_2hw5GHJUFyAknU6wXxHA',
    appId: '1:490084819177:ios:cd516052d96ba2590b1078',
    messagingSenderId: '490084819177',
    projectId: 'pokeproyecto-9c799',
    storageBucket: 'pokeproyecto-9c799.firebasestorage.app',
    iosBundleId: 'com.example.pokeproyecto',
  );
}
